name: build-images

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: write
  security-events: none
  statuses: none

jobs:
  build-images:
    name: Build , test and push docker images for flask apps
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
  
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build and test api docker image
        run: |
          apt-get upgrade curl
          docker build -t opg-flask-api:latest -f rest-api/docker/app/Dockerfile .
          docker run -d -p 8005:8005 -e "AWS_XRAY_SDK_ENABLED=false" opg-flask-api:latest
          docker ps | grep flask-api
          docker logs `docker ps | grep flask-api | awk '{print $NF}'`
          curl --connect-timeout 10 --retry-all-errors --retry 6 --retry-delay 10 -s -w "%{http_code}\n" http://0.0.0.0:8005/healthcheck -o /dev/null
          docker stop `docker ps | grep flask-api | awk '{print $NF}'`

      - name: Build and test front docker image
        run: |
          docker build -t opg-flask-front:latest -f front-app/docker/app/Dockerfile .
          docker run -d -p 8005:8005 -e "AWS_XRAY_SDK_ENABLED=false" opg-flask-front:latest
          #docker logs `docker ps | grep flask-front | awk '{print $NF}'`
          curl --connect-timeout 10 --retry-all-errors --retry 6 --retry-delay 10 -s -w "%{http_code}\n" http://0.0.0.0:8005/healthcheck -o /dev/null
          docker stop `docker ps | grep flask-front | awk '{print $NF}'`
  
      - name: Extract branch name
        run: |
          if [ "${{ github.head_ref }}" == "" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=${{ github.head_ref }} >> $GITHUB_ENV
          fi
        id: extract_branch
      - uses: unfor19/install-aws-cli-action@v1

      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/flask-actions-ci
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 311462405659

      - name: Push api docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opg-flask-apps/rest-api
        run: |
          docker tag opg-flask-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.bump_version.outputs.tag }}
          docker tag opg-flask-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          if [ $BRANCH_NAME == "main" ]; then
            docker tag opg-flask-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ steps.bump_version.outputs.tag }}
            # We want all of the tags pushed
            docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          else
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.bump_version.outputs.tag }}
          fi

